# Generated by Django 5.1.1 on 2025-04-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_add_show_time_to_booking'),
        ('movies', '0004_add_show_time_with_default'),
        ('movies', '0005_add_show_time_with_default'),
    ]

    operations = [
    ]
