# Generated by Django 5.1.1 on 2025-04-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_merge_20250410_2301'),
        ('movies', '0006_set_default_show_time'),
    ]

    operations = [
    ]
