# Generated by Django 5.1.1 on 2025-04-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_allow_null_show_time'),
        ('movies', '0007_merge_20250410_2306'),
    ]

    operations = [
    ]
