# Generated by Django 5.1.1 on 2025-04-10 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_merge_20250410_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.AlterField(
            model_name='booking',
            name='show_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 10, 19, 38, 19, 428926, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ManyToManyField(to='movies.seat'),
        ),
    ]
